[package]
name = "tutor-nodb"
version = "0.1.0"
edition = "2021"
authors = ["Todd Leonhardt"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
actix-rt = "2.9.0"

[[bin]]
name = "basic-server"
